source 'https://rubygems.org'

gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'mysql2'

gem 'rvm-capistrano'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '~> 2.1.3'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
gem 'unicorn'

# For MongoDB
gem 'mongoid'
gem 'bson_ext'

# Para el buscador
gem 'mongoid_fulltext'

# Para los tags en los recursos
#gem 'mongoid_taggable'
gem 'mongoid-simple-tags'

# Para la subida de imágenes
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'

# Para los videos alojados en servicios externos
#gem 'acts_as_unvlogable'
gem 'acts_as_unvlogable', :git => 'http://github.com/alabs/acts_as_unvlogable'

group :development do
  gem 'pry-rails' # a better ruby console
  gem 'rvm-capistrano'
  gem 'capistrano'
  # To use debugger
  #gem 'ruby-debug19', :require => 'ruby-debug'
end

# Para los mapas
gem 'gmaps4rails'

# Para los usuarios
gem 'devise'

# Para la paginacion
gem 'kaminari'

# Recaptcha
gem "recaptcha", :require => "recaptcha/rails"

# authorization
gem 'cancan'

# notificación de excepciones
gem 'exception_notification', :require => 'exception_notifier'

# Para compilar assets
gem 'execjs'
gem 'therubyracer'
#exif info from images
gem 'exifr'
gem 'geocoder'

# Para editar campos al vuelo
gem 'best_in_place'

# Para la edicion de paginas semi estaticas
gem 'mercury-rails'

# para el markdown ed Text 
gem 'redcarpet'

# para el sitemap
gem 'sitemap_generator'

# para los estilos con bootsrap
gem 'nokogiri'

# auth diferentes proveedores
gem 'omniauth-facebook'
#gem 'omniauth-twitter'

# Para generar nombres de usuario
gem "random-word-generator"

#gem 'rvm-capistrano'
